//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SnakesAndLadders.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvatarDesbloqueado
    {
        public int IdAvatarDesbloqueado { get; set; }
        public int AvatarIdAvatar { get; set; }
        public int UsuarioIdUsuario { get; set; }
        public System.DateTime FechaDesbloqueo { get; set; }
    
        public virtual Avatar Avatar { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
