//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SnakesAndLadders.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avatar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Avatar()
        {
            this.AvatarDesbloqueado = new HashSet<AvatarDesbloqueado>();
        }
    
        public int IdAvatar { get; set; }
        public string NombreAvatar { get; set; }
        public string RarezaAvatar { get; set; }
        public Nullable<int> CajaAvatarIdCajaAvatar { get; set; }
        public byte[] Estado { get; set; }
        public string CodigoAvatar { get; set; }
    
        public virtual CajaAvatar CajaAvatar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AvatarDesbloqueado> AvatarDesbloqueado { get; set; }
    }
}
