//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SnakesAndLadders.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contrasenia
    {
        public int IdContrasenia { get; set; }
        public string Contrasenia1 { get; set; }
        public byte[] Estado { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int CuentaIdCuenta { get; set; }
        public int UsuarioIdUsuario { get; set; }
    
        public virtual Cuenta Cuenta { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
