//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SnakesAndLadders.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Objeto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Objeto()
        {
            this.ObjetoUsuario = new HashSet<ObjetoUsuario>();
        }
    
        public int IdObjeto { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> CajaObjetoIdCajaObjeto { get; set; }
        public byte[] Estado { get; set; }
        public string CodigoObjeto { get; set; }
    
        public virtual Caja Caja { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObjetoUsuario> ObjetoUsuario { get; set; }
    }
}
