//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SnakesAndLadders.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaqueteStickers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PaqueteStickers()
        {
            this.StickersUsuario = new HashSet<StickersUsuario>();
        }
    
        public int IdPaqueteStickers { get; set; }
        public string Nombre { get; set; }
        public int Precio { get; set; }
        public byte[] Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StickersUsuario> StickersUsuario { get; set; }
    }
}
