//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SnakesAndLadders.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RedesSociales
    {
        public int IdRedSocial { get; set; }
        public string TipoRedSocial { get; set; }
        public string LinkRedSocial { get; set; }
        public int UsuarioIdUsuario { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
