//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerSnakesAndLadders
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SnakeAndLaddersDBEntities1 : DbContext
    {
        public SnakeAndLaddersDBEntities1()
            : base("name=SnakeAndLaddersDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Avatar> Avatar { get; set; }
        public virtual DbSet<AvatarDesbloqueado> AvatarDesbloqueado { get; set; }
        public virtual DbSet<Caja> Caja { get; set; }
        public virtual DbSet<CajaAvatar> CajaAvatar { get; set; }
        public virtual DbSet<Contrasenia> Contrasenia { get; set; }
        public virtual DbSet<Cuenta> Cuenta { get; set; }
        public virtual DbSet<Dado> Dado { get; set; }
        public virtual DbSet<DadoUsuario> DadoUsuario { get; set; }
        public virtual DbSet<ListaAmigos> ListaAmigos { get; set; }
        public virtual DbSet<Objeto> Objeto { get; set; }
        public virtual DbSet<ObjetoUsuario> ObjetoUsuario { get; set; }
        public virtual DbSet<PaqueteStickers> PaqueteStickers { get; set; }
        public virtual DbSet<Partida> Partida { get; set; }
        public virtual DbSet<RedesSociales> RedesSociales { get; set; }
        public virtual DbSet<Reporte> Reporte { get; set; }
        public virtual DbSet<Sancion> Sancion { get; set; }
        public virtual DbSet<Sticker> Sticker { get; set; }
        public virtual DbSet<StickersUsuario> StickersUsuario { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<UsuarioHasPartida> UsuarioHasPartida { get; set; }
    }
}
