//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerSnakesAndLadders
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reporte
    {
        public int IdReporte { get; set; }
        public string RazonReporte { get; set; }
        public System.DateTime FechaReporte { get; set; }
        public int IdUsuarioReportado { get; set; }
        public int IdUsuarioQueReporta { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
