//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerSnakesAndLadders
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioHasPartida
    {
        public int IdUsuarioHasPartida { get; set; }
        public int UsuarioIdUsuario { get; set; }
        public int PartidaIdPartida { get; set; }
        public byte[] Ganador { get; set; }
    
        public virtual Partida Partida { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
